const {
	REACT_APP_DEV_BASE_URL,
	REACT_APP_AWS_BASE_URL,
	REACT_APP_FRONT_END_URL,
	REACT_APP_DEV_UPLOAD_URL,
} = process.env;

export {
	REACT_APP_DEV_BASE_URL,
	REACT_APP_AWS_BASE_URL,
	REACT_APP_FRONT_END_URL,
	REACT_APP_DEV_UPLOAD_URL,
};
