export const videos = [
  {
    id: 1,
    title: 'The incredible doctor pol',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTy4aRTZv4sQZmvTG75ITcptM25a1NFjKEu9g&usqp=CAU',
    channel: 'National Geographic',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GiHvIK4knTrSNny3m1tIJUhvSoP8-CoyTnlAw=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
    description: 'I show you an implementation of a authentication workflow that uses refresh tokens. The server is written with Node.js, Express, and uses GraphQL. The frontend is written in React. '
  },
  {
    id: 2,
    title: 'The iPhone 12 Pro impression',
    thumbnail: 'https://i.ytimg.com/an_webp/X1b3C2081-Q/mqdefault_6s.webp?du=3000&sqp=CNS32vwF&rs=AOn4CLBTFjntmCGbsiDEaqMbNlad89CT6w',
    channel: 'Marques Brownlee',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Ghl8U3OeJOtu1LRmTNuW7Aiq-iKaU5U6gYWoA=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.5M Views',
    date: '2 Days ago',
    description: 'In this overview we will take a look at Node.js and JSON web tokens. I will show you how to create a route to generate a token and ...'
  },
  {
    id: 3,
    title: 'The Summerian Empire',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfbAmx8sOfMD97o6d9EUkkfIUfR3OsMR9z9Q&usqp=CAU',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Gjn78KG9N2RnEMpzufJLxV6k8S2OjM2Sr330w=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
    description: 'Learn how to automatically refresh your jwt tokens in React. Using afterware, we will check the response from the server every ...',
  },
  {
    id: 4,
    title: 'The incredible doctor pol',
    thumbnail: 'https://www.designcap.com/res/template/medium/771dc0c5a690205f92c9743c78bad6d7/page0.jpg?v=1575618200',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GgCMnjQEkcQnDWswUVSOxK39djnUmCMrbvWwA=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 5,
    title: 'The Summerian Empire',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfbAmx8sOfMD97o6d9EUkkfIUfR3OsMR9z9Q&usqp=CAU',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Gjn78KG9N2RnEMpzufJLxV6k8S2OjM2Sr330w=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 6,
    title: 'The iPhone 12 Pro impression',
    thumbnail: 'https://i.ytimg.com/an_webp/X1b3C2081-Q/mqdefault_6s.webp?du=3000&sqp=CNS32vwF&rs=AOn4CLBTFjntmCGbsiDEaqMbNlad89CT6w',
    channel: 'Marques Brownlee',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Ghl8U3OeJOtu1LRmTNuW7Aiq-iKaU5U6gYWoA=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.5M Views',
    date: '2 Days ago',
  },
  {
    id: 7,
    title: '10 Shoe hacks that will change your life',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQpCU3TLJVqkvM8vvdMYU-VkTP45sLEGSEDGw&usqp=CAU',
    channel: 'TeachingMensFashion',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GgZ-HS3YsQGHz-dQGDOOE9iL-rvyPlsZkGQzg=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 8,
    title: 'The Summerian Empire',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfbAmx8sOfMD97o6d9EUkkfIUfR3OsMR9z9Q&usqp=CAU',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Gjn78KG9N2RnEMpzufJLxV6k8S2OjM2Sr330w=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 9,
    title: 'The incredible doctor pol',
    thumbnail: 'https://www.designcap.com/res/template/medium/771dc0c5a690205f92c9743c78bad6d7/page0.jpg?v=1575618200',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GgCMnjQEkcQnDWswUVSOxK39djnUmCMrbvWwA=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 10,
    title: '10 TOP 7 Sneakers ALL Men Should Buy To Look Cool',
    thumbnail: 'https://i.ytimg.com/an_webp/UUbPjVOcYcs/mqdefault_6s_480x270.webp?du=3000&sqp=CMaQ2vwF&rs=AOn4CLDm0YcXFgYNzhR9nXPxRJX9GSNlaw',
    channel: 'TeachingMensFashion',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GgZ-HS3YsQGHz-dQGDOOE9iL-rvyPlsZkGQzg=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
 
    {
      id: 11,
    title: 'The Summerian Empire',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfbAmx8sOfMD97o6d9EUkkfIUfR3OsMR9z9Q&usqp=CAU',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14Gjn78KG9N2RnEMpzufJLxV6k8S2OjM2Sr330w=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
  {
    id: 12,
    title: 'The incredible doctor pol',
    thumbnail: 'https://www.designcap.com/res/template/medium/771dc0c5a690205f92c9743c78bad6d7/page0.jpg?v=1575618200',
    channel: 'Nat. Geo',
    channelImage: 'https://yt3.ggpht.com/a-/AOh14GgCMnjQEkcQnDWswUVSOxK39djnUmCMrbvWwA=s68-c-k-c0x00ffffff-no-rj-mo',
    views: '2.3M Views',
    date: '4 Days ago',
  },
];